### ISSUE TITLE
Swipe up for quick action doesn't work

### ISSUE THREAD

**Issue by austin6598** [MegaCookie/SwipyFolders#10]
It seems that quick action can only be used with 3D Touching the folder. Can you fix it so that I can swipe up on the folder to see the quick action menu of the first app?

**Comment by JesseVelden** [comment]
Finally fixed in the new version!

**Comment by austin6598** [comment]
I am still having the issue after downloading the newest version from your beta repo
iOS 9.3.2
iPhone 6s (8,1)

**Comment by JesseVelden** [comment]
Interesting, the update for 3D touch was indeed intended for iOS 10 devices. I will take a look into it again :)

**Comment by JesseVelden** [comment]
I have made a new beta, can you try it out?

**Comment by austin6598** [comment]
The quick action menu does show but it requires the user to lift their finger off the screen and then tap to select a menu option. The user can also switch home screen app pages accidentally as they swipe up for quick action. I really appreciate you updating the app to fix the initial bug, and also think an update to address the swipe up action and menu selection as a single gesture would be awesome. You can see in the default 3D touch action that the user can 3D touch and just swipe to select an action without lifting their finger off the screen. [Appendix](http://cydia.saurik.com/package/com.bolencki13.appendix/) also has this feature with folders.

**Comment by JesseVelden** [comment]
I'll take a second look into it. You're right, selecting an quick action without lifting your finger only works with the default force touch gesture yet

**Comment by austin6598** [comment]
Are you still working on this tweak? An iOS 11 update would be much appreciated 👍

**Comment by JesseVelden** [comment]
It's open for pull requests :P, but this is actually a seperate issue. I have another iPad which is jailbroken so I will need to take a look into it. JB stuff is fun but I actually don't like to be my devices a security risk, so that's why I don't like JB that much anymore. Anyway when I feel bored, I will surely work on the tweak again :)
